Imports Microsoft.VisualBasic
Imports System.Data
Imports System.Data.SqlClient
Public Class createDatabase
    Public Shared Function buildDatabase() As Boolean
        Try
            Using conn As New SqlConnection(config.dbConnection)
                Using cmd As New SqlCommand
                    With cmd
                        .Connection = conn
                        .Connection.Open()
                        .CommandText = "IF OBJECT_ID('PS_VERSION', 'U') IS NOT NULL DROP TABLE PS_VERSION; CREATE TABLE [PS_VERSION]([_id] [int] NOT NULL,[version] [varchar](10) NOT NULL,CONSTRAINT [PK_PS_VERSION] PRIMARY KEY CLUSTERED ([_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]; ALTER TABLE [PS_VERSION] ADD  CONSTRAINT [DF_PS_VERSION_version]  DEFAULT ('1.0.0') FOR [version];INSERT INTO PS_VERSION (_id, [version]) VALUES (1, '1.0.0');"
                        .ExecuteNonQuery()
                        .CommandText = "IF OBJECT_ID('PS_CHECK_LIST', 'U') IS NOT NULL DROP TABLE PS_CHECK_LIST; CREATE TABLE [PS_CHECK_LIST]([CHECK_ID] [int] IDENTITY(1,1) NOT NULL,[PS_SITE_ID] [int] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_PS_SITE_ID]  DEFAULT ((1)),[CHECK_NAME] [varchar](100) NOT NULL,[CHECK_FRIENDLY_NAME] [varchar](200) NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_FRIENDLY_NAME]  DEFAULT ('TEMP'),[CHECK_FRIENDLY_DESC] [varchar](200) NULL,[CHECK_API_ID] [varchar](100) NULL,[CHECK_API_SOURCE] [int] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_API_SOURCE]  DEFAULT ((0)),[CHECK_HOSTNAME] [varchar](200) NULL,[CHECK_RESOLUTION] [int] NOT NULL,[CHECK_TYPE] [int] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_TYPE]  DEFAULT ((0)),[CHECK_STATUS] [bit] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_STATUS]  DEFAULT ((0)),[CHECK_STATUS_TEXT] [varchar](10) NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_STATUS_TEXT]  DEFAULT ('down'),[CHECK_LAST_RESPONSE_TIME] [int] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_LAST_RESPONSE_TIME]  DEFAULT ((1000)),[CHECK_LAST_SYNC] [datetime] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_LAST_SYNC]  DEFAULT (getdate()),[CHECK_RUN] [bit] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_RUN]  DEFAULT ((0)),[CHECK_PUBLIC_STATUS] [int] NOT NULL CONSTRAINT [DF_PS_CHECK_LIST_CHECK_PUBLIC_STATUS]  DEFAULT ((1)),CONSTRAINT [PK_PS_CHECK_LIST] PRIMARY KEY CLUSTERED ([CHECK_ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]"
                        .ExecuteNonQuery()
                        .CommandText = "CREATE TABLE [PS_CHECKS]([_ID] [bigint] IDENTITY(1,1) NOT NULL,[CHECK_ID] [int] NOT NULL,[PROBE_ID] [int] NULL,[CHECK_TYPE] [int] NOT NULL CONSTRAINT [DF_Table_1_checkType]  DEFAULT ((0)),[TIME_EPOCH] [bigint] NOT NULL,[TIME_UTC] [datetime] NOT NULL,[STATUS] [varchar](50) NOT NULL CONSTRAINT [DF_Table_1_status]  DEFAULT ('up'),[RESPONSE_TIME] [int] NOT NULL,[STATUSDESC] [varchar](200) NOT NULL,[STATUSDESCLONG] [text] NULL,CONSTRAINT [PK_PS_CHECKS] PRIMARY KEY CLUSTERED ([_ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]"
                        .ExecuteNonQuery() 'IF OBJECT_ID('PS_CHECKS', 'U') IS NOT NULL DROP PS_CHECKS; 
                        .CommandText = "CREATE TABLE [PS_SITES]([PS_SITE_ID] [int] IDENTITY(1,1) NOT NULL,[SITE_DOMAIN] [varchar](200) NOT NULL,[SITE_ENABLED] [bit] NOT NULL CONSTRAINT [DF_PS_SITES_SITE_ENABLED]  DEFAULT ((1)),[SITE_TITLE] [varchar](200) NOT NULL,[SITE_SEARCHABLE] [bit] NOT NULL CONSTRAINT [DF_PS_SITES_SITE_SEARCHABLE]  DEFAULT ((0)),[SITE_ABOUT] [text] NULL,[SITE_INCIDENTS_PAST] [int] NOT NULL CONSTRAINT [DF_PS_SITES_SITE_INCIDENTS_PAST]  DEFAULT ((10)),[SITE_FROM_EMAIL] [text] NOT NULL CONSTRAINT [DF_PS_SITES_SITE_FROM_EMAIL]  DEFAULT ('demo@demo.com'),[SITE_GOOGLE_ANALYTICS] [text] NULL,[SITE_GOSQUARED] [text] NULL,[SITE_SEGMENT] [text] NULL,[SITE_TIMEZONE] [varchar](200) NOT NULL CONSTRAINT [DF_PS_SITES_SITE_TIMEZONE]  DEFAULT ('US Eastern Standard Time'),[SITE_ALLOWED_XSITE] [text] NOT NULL,CONSTRAINT [PK_PS_SITES] PRIMARY KEY CLUSTERED ([PS_SITE_ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]"
                        .ExecuteNonQuery() 'IF OBJECT_ID('PS_SITES', 'U') IS NOT NULL DROP PS_SITES;
                        .Connection.Close()
                    End With
                End Using
            End Using

            Return True

        Catch ex As Exception
            Throw New ApplicationException("Error CREATING DATABASE: " & ex.Message)
        End Try
    End Function
End Class
